apiVersion: v1
kind: Pod
metadata:
  name: eduardotech-nodejs
  labels:
    app: label-pod-eduardotech-nodejs
spec:
  containers:
    - name: container-pod-nodejs
      image: eduardotech/validador-cpf-java
      ports:
        - containerPort: 3000